version: 2

jobs:
  develop:
    branches:
      only:
        - develop
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Install vapor
          command: brew install vapor/tap/vapor
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Deploy to develop
          command: vapor cloud deploy