version: 2

jobs:
  develop:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run:
          name: Install vapor
          command: sudo apt-get install swift vapor
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Deploy to develop
          command: vapor cloud deploy
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - develop