version: 2

jobs:
  develop:
    docker:
      - image: swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Deploy to develop
          command: vapor cloud deploy